fares_catalog_product:
    resource: "@FaresCatalogBundle/Controller/ProductController.php"
    type:     annotation

fares_catalog_category:
    resource: "@FaresCatalogBundle/Controller/CategoryController.php"
    type:     annotation

fares_catalog:
    resource: "@FaresCatalogBundle/Resources/config/routing.xml"
    prefix:   /catalog

app:
    resource: '@AppBundle/Controller/'
    type: annotation
